/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Larissa Guder
 */
public class cadastroAcervo extends javax.swing.JFrame {

    /**
     * Creates new form cadastroAcervo
     */
    public cadastroAcervo() {
        initComponents();
        // centraliza tela
        this.setLocationRelativeTo(null);
        // inutiliza o X
        this.setDefaultCloseOperation(WIDTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cadastrar_acervo = new javax.swing.JButton();
        cancelarCadastro = new javax.swing.JButton();
        tituloCadastro = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox();
        autor = new javax.swing.JTextField();
        issn = new javax.swing.JTextField();
        tipoObra = new javax.swing.JComboBox();
        ano = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSNumeroExemplar = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("*Título: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("*Autor:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("*Gênero: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("*Tipo Obra:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("ISSN:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("*Ano:");

        Cadastrar_acervo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Create New-26.png"))); // NOI18N
        Cadastrar_acervo.setText("Cadastrar");
        Cadastrar_acervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_acervoActionPerformed(evt);
            }
        });

        cancelarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Delete-26 (1).png"))); // NOI18N
        cancelarCadastro.setText("Cancelar");
        cancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastroActionPerformed(evt);
            }
        });

        tituloCadastro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tituloCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloCadastroActionPerformed(evt);
            }
        });
        tituloCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloCadastroKeyReleased(evt);
            }
        });

        genero.setMaximumRowCount(25);
        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "AÇÃO", "AVENTURA", "AUTOAJUDA", "CIÊNCIA", "CULINÁRIA | GASTRONOMIA", "ESOTERISMO", "FANTASIA | FICÇÃO", "FILOSOFIA", "GUERRA", "HISTÓRIA", "LINGUÍSTICA", "LIT. ESTRANGEIRA", "LIT. INFANTO-JUVENIL", "LIT. NACIONAL", "MEDICINA", "MÚSICA", "POLÍTICA", "PSICOLOGIA", "ROMANCE", "QUADRINHOS", "RELIGIÃO", "SAÚDE", "SEXO", "TERROR", "VESTIBULAR", "CRÔNICA", "POESIA", "POEMAS" }));
        genero.setToolTipText("");

        autor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        autor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                autorKeyReleased(evt);
            }
        });

        issn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tipoObra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "LIVRO", "REVISTA", "CD", "DVD", "MANGÁ", "HQ" }));
        tipoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoObraActionPerformed(evt);
            }
        });

        ano.setMaximumSize(new java.awt.Dimension(4, 4));
        ano.setMinimumSize(new java.awt.Dimension(4, 4));
        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Erase-26.png"))); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Campos marcados com * são obrigatórios.");

        jSNumeroExemplar.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSNumeroExemplar.setValue(1);

        jLabel8.setText("Número de Exemplares");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cadastrar_acervo)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarCadastro)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSNumeroExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(tipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSNumeroExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar_acervo)
                    .addComponent(cancelarCadastro)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloCadastroActionPerformed

    private void cancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastroActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarCadastroActionPerformed

    private void Cadastrar_acervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_acervoActionPerformed
        CadastroAcervoClass AddObra = new CadastroAcervoClass();

        if (tituloCadastro.getText().isEmpty() || genero.getSelectedItem() == "Selecione" || tipoObra.getSelectedItem() == "Selecione" || autor.getText().isEmpty() || ano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Todos os campos marcados com * devem ser preenchidos");

        }
        if (ano.getText().length() != 4) {
            JOptionPane.showMessageDialog(rootPane, "Reveja informações do campo ANO");

        } else {
            int numero = ((SpinnerNumberModel) jSNumeroExemplar.getModel()).getNumber().intValue();

            for (int i = 0; numero > i; i++) {
                AddObra.inserir_obra(tituloCadastro.getText(), genero.getSelectedItem().toString(), tipoObra.getSelectedItem().toString(), autor.getText(), issn.getText(), ano.getText());

            }

            tituloCadastro.setText("");
            autor.setText("");
            issn.setText("");
            ano.setText("");

        }


    }//GEN-LAST:event_Cadastrar_acervoActionPerformed

    private void tipoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoObraActionPerformed

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tituloCadastro.setText("");
        autor.setText("");
        issn.setText("");
        ano.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tituloCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloCadastroKeyReleased
        tituloCadastro.setText(tituloCadastro.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloCadastroKeyReleased

    private void autorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_autorKeyReleased
        autor.setText(autor.getText().toUpperCase());

// TODO add your handling code here:
    }//GEN-LAST:event_autorKeyReleased
    /**
     * public void inserir_obra(String a1, String a2, String a3, String a4,
     * String a5, String a6){ Conec_BD in = new Conec_BD(); try {
     * Class.forName(in.driver); } catch (ClassNotFoundException ex) {
     * Logger.getLogger(cadastroAcervo.class.getName()).log(Level.SEVERE, null,
     * ex); } try { Connection con = DriverManager.getConnection(in.url,in.
     * nome, in.senha); PreparedStatement banco_acervo =
     * con.prepareStatement("insert into acervo values (?, ?, ?, ?, ?, ?, ?) ");
     * banco_acervo.setString(1, a1); banco_acervo.setString(2, a2);
     * banco_acervo.setString(3, a3); banco_acervo.setString(4, a4);
     * banco_acervo.setString(5, a5); banco_acervo.setString(6, a6);
     * banco_acervo.setString(7, "DISPONÍVEL");
     *
     * banco_acervo.executeUpdate(); JOptionPane.showMessageDialog(null,"Obra
     * Cadastrada");
     *
     *
     * this.dispose();
     *
     *
     *
     * } catch (SQLException ex) { JOptionPane.showMessageDialog(null, "ERRO");
     * Logger.getLogger(cadastroAcervo.class.getName()).log(Level.SEVERE, null,
     * ex); } }
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroAcervo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar_acervo;
    private javax.swing.JTextField ano;
    private javax.swing.JTextField autor;
    private javax.swing.JButton cancelarCadastro;
    private javax.swing.JComboBox genero;
    private javax.swing.JTextField issn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSNumeroExemplar;
    private javax.swing.JComboBox tipoObra;
    private javax.swing.JTextField tituloCadastro;
    // End of variables declaration//GEN-END:variables
}
