/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Larissa Guder
 */
public class consultaAcervo extends javax.swing.JFrame {

    String codigo;

    /**
     * Creates new form consultaAcervo
     */
    public consultaAcervo() {
        initComponents();
        this.setLocationRelativeTo(null);
        // inutiliza o X
        this.setDefaultCloseOperation(WIDTH);
    }

    public void filtro() {

        DefaultTableModel tabelaAcervo = new DefaultTableModel();

        tabelaAcervo.addColumn("Título");
        tabelaAcervo.addColumn("Código");
        tabelaAcervo.addColumn("Gênero");
        tabelaAcervo.addColumn("Tipo de Obra");
        tabelaAcervo.addColumn("Status");
        tabelaAcervo.addColumn("Autor");
        tabelaAcervo.addColumn("Ano");
        tabelaAcervo.addColumn("ISSN");

        CadastroAcervoClass acervo = new CadastroAcervoClass();

        ArrayList<CadastroAcervoClass> dados = null;

// = acervo.listar_livros("select * from acervo where titulo like '%" + BuscaTitulo.getText() + "%'");;
        if (!tituloCadastro.getText().isEmpty()) {
            dados = acervo.listar_livros("select * from acervo where titulo like '%" + tituloCadastro.getText() + "%'");
        }

        if (!jTCodigo.getText().isEmpty()) {
            int cod1 = Integer.parseInt(jTCodigo.getText());

            dados = acervo.listar_livros("select * from acervo where cod_obra = " + cod1 + "");

        }
        if (!autor.getText().isEmpty() || !issn.getText().isEmpty() || !ano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Busca por item no acervo somente através do título ou do código.");
            autor.setText(null);
            issn.setText(null);
            ano.setText(null);

        }

        for (CadastroAcervoClass base : dados) {

            tabelaAcervo.addRow(new Object[]{base.titulo, base.codigo, base.genero, base.tipoObra, base.status, base.autor, base.ano, base.ISSN});

        }

        jTBusca.setModel(tabelaAcervo);
    }

    public void filtroInicio() {

        DefaultTableModel tabelaAcervo = new DefaultTableModel();

        tabelaAcervo.addColumn("Título");
        tabelaAcervo.addColumn("Código");
        tabelaAcervo.addColumn("Gênero");
        tabelaAcervo.addColumn("Tipo de Obra");
        tabelaAcervo.addColumn("Status");
        tabelaAcervo.addColumn("Autor");
        tabelaAcervo.addColumn("Ano");
        tabelaAcervo.addColumn("ISSN");

        CadastroAcervoClass acervo = new CadastroAcervoClass();

        ArrayList<CadastroAcervoClass> dados = null;

// = acervo.listar_livros("select * from acervo where titulo like '%" + BuscaTitulo.getText() + "%'");;
        dados = acervo.listar_livros("select * from acervo");

        for (CadastroAcervoClass base : dados) {

            tabelaAcervo.addRow(new Object[]{base.titulo, base.codigo, base.genero, base.tipoObra, base.status, base.autor, base.ano, base.ISSN});

        }

        jTBusca.setModel(tabelaAcervo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTBusca = new javax.swing.JTable();
        jLObra = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jLISSN = new javax.swing.JLabel();
        jLAutor = new javax.swing.JLabel();
        jLGenero = new javax.swing.JLabel();
        tituloCadastro = new javax.swing.JTextField();
        jTCodigo = new javax.swing.JTextField();
        autor = new javax.swing.JTextField();
        issn = new javax.swing.JTextField();
        jBProcurar = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        genero = new javax.swing.JComboBox();
        jBeditar = new javax.swing.JButton();
        jLAno = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        tipoObra = new javax.swing.JComboBox();
        jLTipo = new javax.swing.JLabel();
        jBexcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título da obra", "Gênero", "Tipo da Obra", "Autor", "ISSN", "Ano", "Disponibilidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTBusca);

        jLObra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLObra.setText("Nome da obra:");

        jLCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCodigo.setText("Código:");

        jLISSN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLISSN.setText("ISSN:");

        jLAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLAutor.setText("Autor:");

        jLGenero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLGenero.setText("Gênero: ");

        tituloCadastro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tituloCadastroPropertyChange(evt);
            }
        });
        tituloCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloCadastroKeyReleased(evt);
            }
        });

        autor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                autorKeyReleased(evt);
            }
        });

        jBProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Binoculars-26.png"))); // NOI18N
        jBProcurar.setText("Procurar");
        jBProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcurarActionPerformed(evt);
            }
        });

        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Erase-26.png"))); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Delete-26 (1).png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        genero.setMaximumRowCount(25);
        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Ação", "Aventura", "Auto-Ajuda", "Ciência", "Culinária | Gastronomia", "Esoterismo", "Fantasia | Ficção", "Filosofia", "Guerra", "História", "Lingüistica", "Lit. Estrangeira", "Lit. Infanto-Juvenil", "Lit. Nacional", "Medicina", "Música", "Política", "Psicologia", "Romance", "Quadrinhos", "Religião", "Saúde", "Sexo", "Terror", "Vestibular", "Cronica", "Poesia", "Poemas" }));

        jBeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Edit-26.png"))); // NOI18N
        jBeditar.setText("Editar");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        jLAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLAno.setText("Ano:");

        tipoObra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Livro", "Revista", "CD", "DVD", "Mangá", "HQ" }));
        tipoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoObraActionPerformed(evt);
            }
        });

        jLTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTipo.setText("Tipo da Obra:");

        jBexcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Larissa Guder\\Downloads\\Delete-26.png")); // NOI18N
        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/View Details-26.png"))); // NOI18N
        jBListar.setText("Listar Todas Obras");
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLObra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLGenero)
                                .addGap(18, 18, 18)
                                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigo)
                            .addComponent(jLAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autor, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jTCodigo))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTipo)
                                .addGap(18, 18, 18)
                                .addComponent(tipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLISSN)
                        .addGap(18, 18, 18)
                        .addComponent(issn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jBexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBeditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBListar)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLCodigo)
                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLAno)
                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAutor)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLGenero)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLISSN)
                    .addComponent(jBeditar)
                    .addComponent(jBexcluir)
                    .addComponent(jBListar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(178, 178, 178))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCancelar)
                            .addComponent(jBLimpar)
                            .addComponent(jBProcurar))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcurarActionPerformed
        filtro();        // TODO add your handling code here:
    }//GEN-LAST:event_jBProcurarActionPerformed

    private void tipoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoObraActionPerformed

    private void jTBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBuscaMouseClicked
        int linha_selecionada = jTBusca.getSelectedRow();
        tituloCadastro.setText(jTBusca.getValueAt(linha_selecionada, 0).toString());
        autor.setText(jTBusca.getValueAt(linha_selecionada, 5).toString());
        issn.setText(jTBusca.getValueAt(linha_selecionada, 7).toString());
        ano.setText(jTBusca.getValueAt(linha_selecionada, 6).toString());
        codigo = jTBusca.getValueAt(linha_selecionada, 1).toString();

    }//GEN-LAST:event_jTBuscaMouseClicked

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
        emprestimos AddObra = new emprestimos();
        // int contador = Integer.parseInt(AddObra.gera_codigo())+ 1;
        // String codigo = Integer.toString(contador);
        AddObra.editarObra(tituloCadastro.getText(), genero.getSelectedItem().toString(), tipoObra.getSelectedItem().toString(), autor.getText(), issn.getText(), ano.getText(), codigo);
    }//GEN-LAST:event_jBeditarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        emprestimos excluir = new emprestimos();

        excluir.excluiObra(tituloCadastro.getText());
        tituloCadastro.setText(null);
        autor.setText(null);
        issn.setText(null);
        ano.setText(null);
        jTCodigo.setText(null);
        filtroInicio();
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed

        tituloCadastro.setText(null);
        autor.setText(null);
        issn.setText(null);
        ano.setText(null);
        jTCodigo.setText(null);

// TODO add your handling code here:
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
        filtroInicio();        // TODO add your handling code here:
    }//GEN-LAST:event_jBListarActionPerformed

    private void tituloCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloCadastroKeyReleased
        tituloCadastro.setText(tituloCadastro.getText().toUpperCase());

        // TODO add your handling code here:
    }//GEN-LAST:event_tituloCadastroKeyReleased

    private void autorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_autorKeyReleased
        autor.setText(autor.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_autorKeyReleased

    private void tituloCadastroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tituloCadastroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloCadastroPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaAcervo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JTextField autor;
    private javax.swing.JComboBox genero;
    private javax.swing.JTextField issn;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBListar;
    private javax.swing.JButton jBProcurar;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JLabel jLAno;
    private javax.swing.JLabel jLAutor;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLISSN;
    private javax.swing.JLabel jLObra;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTBusca;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JComboBox tipoObra;
    private javax.swing.JTextField tituloCadastro;
    // End of variables declaration//GEN-END:variables

}
