package my;

/**
 *
 * @author Larissa Guder
 */
public class telaPadrao extends javax.swing.JFrame {

    /**
     * Creates new form telaPadrao
     */
    public telaPadrao() {
        initComponents();
        this.setLocationRelativeTo(null);

        // centraliza tela
        this.setLocationRelativeTo(null);
        // inutiliza o X

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        sair = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        acervo = new javax.swing.JMenu();
        cadastrarObra = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        emprestarObra = new javax.swing.JMenuItem();
        DevolucaoObra = new javax.swing.JMenuItem();
        jMIRenovar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMCadastrarUsuario = new javax.swing.JMenuItem();
        jMPequisarUsuariio = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Biblioteca");
        setBackground(new java.awt.Color(162, 29, 162));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/School-100 (2).png"))); // NOI18N
        jLabel1.setFocusTraversalPolicyProvider(true);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Exit-26.png"))); // NOI18N
        sair.setText("Arquivo");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        sair.add(jMenuItem3);

        menu.add(sair);

        acervo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Courses-26.png"))); // NOI18N
        acervo.setText("Acervo");

        cadastrarObra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        cadastrarObra.setText("Cadastrar Obra");
        cadastrarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarObraActionPerformed(evt);
            }
        });
        acervo.add(cadastrarObra);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Procurar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        acervo.add(jMenuItem4);

        emprestarObra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        emprestarObra.setText("Emprestar");
        emprestarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestarObraActionPerformed(evt);
            }
        });
        acervo.add(emprestarObra);

        DevolucaoObra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        DevolucaoObra.setText("Devolver");
        DevolucaoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucaoObraActionPerformed(evt);
            }
        });
        acervo.add(DevolucaoObra);

        jMIRenovar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMIRenovar.setText("Renovar");
        jMIRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRenovarActionPerformed(evt);
            }
        });
        acervo.add(jMIRenovar);

        menu.add(acervo);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/User Group-26.png"))); // NOI18N
        jMenu2.setText("Leitores");

        jMCadastrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMCadastrarUsuario.setText("Cadastrar Usuário");
        jMCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMCadastrarUsuario);

        jMPequisarUsuariio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMPequisarUsuariio.setText("Pesquisar Usuário");
        jMPequisarUsuariio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPequisarUsuariioActionPerformed(evt);
            }
        });
        jMenu2.add(jMPequisarUsuariio);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Histórico de Retiradas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(557, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarObraActionPerformed
        cadastroAcervo frame = new cadastroAcervo();

        frame.setVisible(true);
    }//GEN-LAST:event_cadastrarObraActionPerformed

    private void jMCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarUsuarioActionPerformed
        cadastroUsuario frame = new cadastroUsuario();
        frame.setVisible(true);

    }//GEN-LAST:event_jMCadastrarUsuarioActionPerformed

    private void jMPequisarUsuariioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPequisarUsuariioActionPerformed
        Consulta_Usuario frame = new Consulta_Usuario();
        frame.setVisible(true);

    }//GEN-LAST:event_jMPequisarUsuariioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void emprestarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestarObraActionPerformed
        EmprestimosClass frame = new EmprestimosClass();
        frame.setVisible(true);

    }//GEN-LAST:event_emprestarObraActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        consultaAcervo frame = new consultaAcervo();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void DevolucaoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucaoObraActionPerformed
        Devolucao frame = new Devolucao();
        frame.setVisible(true);


    }//GEN-LAST:event_DevolucaoObraActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        HistoricoRetiradas frame = new HistoricoRetiradas();
        frame.setVisible(true);


    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMIRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRenovarActionPerformed
        RenovarAcervo frame = new RenovarAcervo();
        frame.setVisible(true);

    }//GEN-LAST:event_jMIRenovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DevolucaoObra;
    private javax.swing.JMenu acervo;
    private javax.swing.JMenuItem cadastrarObra;
    private javax.swing.JMenuItem emprestarObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMCadastrarUsuario;
    private javax.swing.JMenuItem jMIRenovar;
    private javax.swing.JMenuItem jMPequisarUsuariio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables
}
